site_name: pyptsca.github.io
theme:
  name: material
  language: zh
  features:
    - navigation.tabs       # 启用顶部导航选项卡
    - navigation.top        # 显示返回顶部按钮
    - navigation.indexes    # 允许子目录有索引页 (如 directory/index.md)
    #- toc.integrate         # 将页面内目录集成到侧边栏导航中
    - search.suggest        # 搜索建议
    - search.highlight      # 搜索结果高亮
    - content.tabs          # 在 Markdown 中使用选项卡 (如 ```tabs)
    - content.code.copy     # 为代码块添加复制按钮
    #- content.action.edit   # 在页面底部显示编辑链接 (需配置 edit_uri)

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到亮色模式        # 配色方案配置，支持亮色/暗色切换
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: 切换到亮色模式

repo_url: https://github.com/PYPTsca/pyptsca.github.io/ # 右上角点击跳转的链接
repo_name: pyptsca.github.io # 右上角的名字

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true # 显示行号
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # 代码块增强，支持嵌套内容
  - admonition   # 提示块
  - pymdownx.details  # 可折叠的提示块
  - pymdownx.tabbed:      # 选项卡
      alternate_style: true
  - pymdownx.tasklist:    # 任务列表
      custom_checkbox: true
  - attr_list             # 为元素添加 HTML 属性
  - md_in_html            # 在 HTML 块内渲染 Markdown
  - tables                # 表格
  - footnotes             # 脚注
  - pymdownx.emoji:       # Emoji 表情
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    
plugins:
  - search

nav:
  - 玩《魔法少女的魔女审判》艾玛有感: 'index.md'
  - MkDocs 完全使用教程: 'about.md'